name = "api-5025"
main = "src/index.ts"
compatibility_date = "2026-06-01"
compatibility_flags = ["nodejs_compat"]

[vars]
COOKIE_SAMESITE = "None"
COOKIE_SECURE = "true"
SUPABASE_STORAGE_BUCKET = "mission-photos"
TOSS_CLIENT_KEY = "test_ck_D5GePWvyJnrK0W0k6q8gLzN97Eoq"

# Set TOSS_SECRET_KEY with `wrangler secret put TOSS_SECRET_KEY`.

[[hyperdrive]]
binding = "HYPERDRIVE"
id = "15de82730d734a329a044a43fcf47678"
